services:
  reactive-api:
    image: "laurocorreia/reactive-api:latest"
    container_name: "reactive-api"
    networks:
      - compose-bridge
    ports:
      - 8080:8080
networks:
  compose-bridge:
    driver: bridge